### ISSUE TITLE
Missing SampleProject folder

### ISSUE THREAD

**Issue by trsh** [sceelix/Sceelix#12]
In `Sceelix.MyExternalApplication` there is no `SampleProject` folder. It shows up in Visual Studio solution, but is physically missing. I used windows 64 bit installer.

**Comment by pabsilva** [comment]
Ah, indeed, I realize that some resources weren't packed in the zip. Are these what you mean? You can still see the Program.cs and Readme, right?

![image](https://user-images.githubusercontent.com/1540991/129477788-5316e352-bee6-479d-8709-3778d39ca917.png)

**Comment by trsh** [comment]
Yes. I ended up copying `City.slxg` over with all assets and submodules. But I am getting this error with out the exact line. Please tell me what I am doing wrong.

[Sceelix.MyExternalApplication.zip](https://github.com/sceelix/Sceelix/files/6988121/Sceelix.MyExternalApplication.zip)

```
System.InvalidCastException: Specified cast is not valid.
   at Sceelix.Extensions.XmlNodeExtension.GetAttributeOrDefault[T](XmlNode node, String attributeName)
   at Sceelix.Core.Graphs.GraphLoad.LoadNodes(XmlElement root, Graph graph, IProcedureEnvironment procedureEnvironment, Dictionary`2 graphCache)
```

**Comment by pabsilva** [comment]
I got it working on my side, but only after adjusting the assembly references. If I'm looking at it correctly, you have installed Sceelix under `C:\Engines\Sceelix`, so the library assemblies are under `C:\Engines\Sceelix\Bin`. Are your project assembly references also pointing to these same assemblies?

![image](https://user-images.githubusercontent.com/1540991/129485116-a0a86403-8997-4825-b480-a96c0db1da9e.png)

**Comment by trsh** [comment]
> I got it working on my side, but only after adjusting the assembly references. If I'm looking at it correctly, you have installed Sceelix under `C:\Engines\Sceelix`, so the library assemblies are under `C:\Engines\Sceelix\Bin`. Are your project assembly references also pointing to these same assemblies?
> 
> ![image](https://user-images.githubusercontent.com/1540991/129485116-a0a86403-8997-4825-b480-a96c0db1da9e.png)

Yes

**Comment by trsh** [comment]
When I change the line I am getting these:

```
System.Exception: Could not find type 'PathCreateProcedure'.
The procedure may have been moved, deleted or simply not loaded.
   at Sceelix.Core.Procedures.InvalidProcedure.Run()
   at Sceelix.Core.Procedures.Procedure.ExecuteRound()
Sceelix.Core.Exceptions.GraphException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Sceelix.Core.IO.OutputReferenceCollection.get_Item(Int32 index)
   at Sceelix.Core.Graphs.Execution.ExecutionNode.Execute()
   --- End of inner exception stack trace ---
   at Sceelix.Core.Graphs.Execution.ExecutionNode.Execute()
   at Sceelix.Core.Procedures.GraphProcedure.Run()
   at Sceelix.Core.Procedures.Procedure.ExecuteRound()
Finished Execution.
```

**Comment by trsh** [comment]
Never mind. Needed to add the required DLL.
